inkscape: fixup floors

diff --git a/packages/tools-floors/scripts/inkex-python b/packages/tools-floors/scripts/inkex-python
--- a/packages/tools-floors/scripts/inkex-python
+++ b/packages/tools-floors/scripts/inkex-python
@@ -1,5 +1,24 @@
 #!/bin/sh
 
-. $( dirname "$0" )/inkex-setup
+pkgdir=
+if [ -n "$NODE_PATH" ]; then
+  paths=$NODE_PATH
+  while :; do
+    d=${paths%%/node_modules:*}
+    paths=${paths#*:}
+    [ -e "$d"/package.json ] && pkgdir="$d" && break
+    [ "$d"/node_modules = "$paths" ] && echo >&2 'package directory not found!' && exit 1
+  done
+else
+  pkgdir=$( cd $( dirname $0 ); cd ..; pwd )
+fi
+
+####
+
+tools="$pkgdir"/scripts
+
+export UV_PROJECT="$pkgdir"
+
+. "$tools"/inkex-setup
 
 env PYTHONPATH="${extensions}" uv run python "$@"
